version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - db_mysql:/var/lib/mysql # Persist data
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - primeira-network

    api-rocket:
      container_name: api_rocket
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3001:3000
      depends_on:
        - mysql
      networks:
        - primeira-network

networks:
  primeira-network:
    name: primeira-network
    external: true # it will use the existing network
    driver: bridge

volumes:
  db_mysql:
