name: CI

on:
  push:
    branches:
      - main
    paths:
      - "./example-nestjs/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "./example-nestjs/**"
      - ".github/workflows/ci.yml"

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js | ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: ./example-nestjs/yarn.lock

      - run: yarn install
        working-directory: ./example-nestjs

      - run: yarn run test
        working-directory: ./example-nestjs
